version: "3.3"

services:
  cassandra-seed:
    image: cassandra:latest
    ports:
      - "9044:9042"
    volumes:
      - "./cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Panda Cluster"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=200M"
    restart: always

  cassandra1:
    image: cassandra:latest
    volumes:
      - "./cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Panda Cluster"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=200M"
    depends_on:
      - cassandra-seed
    restart: always

volumes:
  cassandra_data_seed:
  cassandra_data_1: