name: Dependency Check
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Dependency Check Report
        run: sbt dependencyCheckAggregate
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report.html
          path: target/scala-2.13/dependency-check-report.html
          retention-days: 30
